[14-Jan-2020 22:09:02 Africa/Johannesburg] PHP Warning:  Use of undefined constant STDERR - assumed 'STDERR' (this will throw an Error in a future version of PHP) in /home/insuran3/public_html/training/lib/clilib.php on line 183
[14-Jan-2020 22:09:02 Africa/Johannesburg] PHP Warning:  fwrite() expects parameter 1 to be resource, string given in /home/insuran3/public_html/training/lib/clilib.php on line 36
[18-Jan-2020 12:00:01 Africa/Johannesburg] Default exception handler: Could not connect to the specified authentication database... Debug: 
Error code: auth_dbcantconnect
* line 494 of /lib/setuplib.php: moodle_exception thrown
* line 528 of /auth/db/auth.php: call to print_error()
* line 297 of /auth/db/auth.php: call to auth_plugin_db->get_userlist()
* line 102 of /auth/db/cli/sync_users.php: call to auth_plugin_db->sync_users()

[19-Jan-2020 12:00:02 Africa/Johannesburg] Default exception handler: Could not connect to the specified authentication database... Debug: 
Error code: auth_dbcantconnect
* line 494 of /lib/setuplib.php: moodle_exception thrown
* line 528 of /auth/db/auth.php: call to print_error()
* line 297 of /auth/db/auth.php: call to auth_plugin_db->get_userlist()
* line 102 of /auth/db/cli/sync_users.php: call to auth_plugin_db->sync_users()

[20-Jan-2020 12:00:01 Africa/Johannesburg] Default exception handler: Could not connect to the specified authentication database... Debug: 
Error code: auth_dbcantconnect
* line 494 of /lib/setuplib.php: moodle_exception thrown
* line 528 of /auth/db/auth.php: call to print_error()
* line 297 of /auth/db/auth.php: call to auth_plugin_db->get_userlist()
* line 102 of /auth/db/cli/sync_users.php: call to auth_plugin_db->sync_users()

[20-Jan-2020 14:41:02 Africa/Johannesburg] Default exception handler: Could not connect to the specified authentication database... Debug: 
Error code: auth_dbcantconnect
* line 494 of /lib/setuplib.php: moodle_exception thrown
* line 528 of /auth/db/auth.php: call to print_error()
* line 297 of /auth/db/auth.php: call to auth_plugin_db->get_userlist()
* line 102 of /auth/db/cli/sync_users.php: call to auth_plugin_db->sync_users()

[20-Jan-2020 14:42:02 Africa/Johannesburg] Default exception handler: Could not connect to the specified authentication database... Debug: 
Error code: auth_dbcantconnect
* line 494 of /lib/setuplib.php: moodle_exception thrown
* line 528 of /auth/db/auth.php: call to print_error()
* line 297 of /auth/db/auth.php: call to auth_plugin_db->get_userlist()
* line 102 of /auth/db/cli/sync_users.php: call to auth_plugin_db->sync_users()

[20-Jan-2020 14:43:01 Africa/Johannesburg] Default exception handler: Could not connect to the specified authentication database... Debug: 
Error code: auth_dbcantconnect
* line 494 of /lib/setuplib.php: moodle_exception thrown
* line 528 of /auth/db/auth.php: call to print_error()
* line 297 of /auth/db/auth.php: call to auth_plugin_db->get_userlist()
* line 102 of /auth/db/cli/sync_users.php: call to auth_plugin_db->sync_users()

[20-Jan-2020 14:44:02 Africa/Johannesburg] Default exception handler: Could not connect to the specified authentication database... Debug: 
Error code: auth_dbcantconnect
* line 494 of /lib/setuplib.php: moodle_exception thrown
* line 528 of /auth/db/auth.php: call to print_error()
* line 297 of /auth/db/auth.php: call to auth_plugin_db->get_userlist()
* line 102 of /auth/db/cli/sync_users.php: call to auth_plugin_db->sync_users()

[20-Jan-2020 14:45:02 Africa/Johannesburg] Default exception handler: Could not connect to the specified authentication database... Debug: 
Error code: auth_dbcantconnect
* line 494 of /lib/setuplib.php: moodle_exception thrown
* line 528 of /auth/db/auth.php: call to print_error()
* line 297 of /auth/db/auth.php: call to auth_plugin_db->get_userlist()
* line 102 of /auth/db/cli/sync_users.php: call to auth_plugin_db->sync_users()

